# -*- coding: utf-8 -*-
"""Inceptionv3+CBAM_Pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFLwLIqqZEP09Km_9FT3vJNvb1W7hNpO
"""

from google.colab import files
files.upload()  

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d masoudnickparvar/brain-tumor-mri-dataset

!unzip -q brain-tumor-mri-dataset.zip

"""BLOCK 1: Import Libraries"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets, models
from torch.utils.data import DataLoader, WeightedRandomSampler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt

"""BLOCK 2: Set directory paths for training/testing"""

import os

print("Train classes:", os.listdir("/content/Training"))
print("Test classes:", os.listdir("/content/Testing"))

train_dir = "/content/Training" 
test_dir = "/content/Testing"

"""BLOCK 3: Data Augmentation, Class Weights & Balanced Sampler"""

train_transforms = transforms.Compose([
    transforms.Resize((150, 150)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.RandomResizedCrop(150, scale=(0.9, 1.0)),
    transforms.ToTensor(),
])

test_transforms = transforms.Compose([
    transforms.Resize((150, 150)),
    transforms.ToTensor(),
])

train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
test_dataset = datasets.ImageFolder(test_dir, transform=test_transforms)

train_labels = [label for _, label in train_dataset]

class_weights = compute_class_weight('balanced', classes=np.unique(train_labels), y=train_labels)
class_weights = torch.tensor(class_weights, dtype=torch.float)

print("Class weights:", class_weights)

class_counts = np.bincount(train_labels)
sample_weights = [1.0 / class_counts[label] for label in train_labels]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=sampler)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

class_names = train_dataset.classes
print("Classes:", class_names)

"""BLOCK 4: Define CBAM Block & InceptionV3 Model with Attention"""

from torchvision.models import inception_v3, Inception_V3_Weights

class CBAM(nn.Module):
    def __init__(self, channels, reduction_ratio=8):
        super(CBAM, self).__init__()
        # Channel Attention
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)

        self.shared_mlp = nn.Sequential(
            nn.Conv2d(channels, channels // reduction_ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(channels // reduction_ratio, channels, 1, bias=False)
        )

        self.sigmoid_channel = nn.Sigmoid()

        # Spatial Attention
        self.conv_spatial = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid_spatial = nn.Sigmoid()

    def forward(self, x):
        # Channel attention
        avg_out = self.shared_mlp(self.avg_pool(x))
        max_out = self.shared_mlp(self.max_pool(x))
        channel_att = self.sigmoid_channel(avg_out + max_out)
        x = x * channel_att

        # Spatial attention
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        spatial_att = self.sigmoid_spatial(self.conv_spatial(torch.cat([avg_out, max_out], dim=1)))
        x = x * spatial_att

        return x

# InceptionV3 + CBAM model
class InceptionCBAM(nn.Module):
    def __init__(self, num_classes=4):
        super(InceptionCBAM, self).__init__()
        self.backbone = inception_v3(weights=Inception_V3_Weights.DEFAULT, aux_logits=True)  
        self.backbone.AuxLogits.fc = nn.Linear(768, num_classes)
        self.backbone.fc = nn.Identity()

        self.cbam = CBAM(2048)
        self.pool = nn.AdaptiveAvgPool2d((1, 1))

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(2048, 256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.backbone.Conv2d_1a_3x3(x)
        x = self.backbone.Conv2d_2a_3x3(x)
        x = self.backbone.Conv2d_2b_3x3(x)
        x = self.backbone.maxpool1(x)
        x = self.backbone.Conv2d_3b_1x1(x)
        x = self.backbone.Conv2d_4a_3x3(x)
        x = self.backbone.maxpool2(x)

        x = self.backbone.Mixed_5b(x)
        x = self.backbone.Mixed_5c(x)
        x = self.backbone.Mixed_5d(x)
        x = self.backbone.Mixed_6a(x)
        x = self.backbone.Mixed_6b(x)
        x = self.backbone.Mixed_6c(x)
        x = self.backbone.Mixed_6d(x)
        x = self.backbone.Mixed_6e(x)
        x = self.backbone.Mixed_7a(x)
        x = self.backbone.Mixed_7b(x)
        x = self.backbone.Mixed_7c(x)

        x = self.cbam(x)
        x = self.pool(x)
        x = self.classifier(x)
        return x

"""BLOCK 5: Setup Device, Model, Loss Function, Optimizer"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = InceptionCBAM(num_classes=len(class_names)).to(device)

criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

"""BLOCK 6: Training and Validation Loop"""

def train(model, train_loader, val_loader, criterion, optimizer, epochs=15):
    train_losses, val_losses = [], []
    train_accuracies, val_accuracies = [], []

    best_val_acc = 0.0
    best_model_path = "best_model.pth"

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss = 0.0
        correct_preds = 0
        total_preds = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            preds = torch.argmax(outputs, dim=1)
            correct_preds += (preds == labels).sum().item()
            total_preds += labels.size(0)

        train_loss = running_loss / total_preds
        train_acc = correct_preds / total_preds

        # Validation phase
        model.eval()
        val_running_loss = 0.0
        val_correct_preds = 0
        val_total_preds = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)

                val_running_loss += loss.item() * images.size(0)
                preds = torch.argmax(outputs, dim=1)
                val_correct_preds += (preds == labels).sum().item()
                val_total_preds += labels.size(0)

        val_loss = val_running_loss / val_total_preds
        val_acc = val_correct_preds / val_total_preds

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accuracies.append(train_acc)
        val_accuracies.append(val_acc)

        print(f"Epoch [{epoch}/{epochs}] | "
              f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f} | "
              f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

        # Save best model
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save({
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'class_names': class_names,
                'epoch': epoch,
                'val_acc': val_acc
            }, best_model_path)
            print(f"Best model saved at epoch {epoch} with val_acc {val_acc:.4f}")

    return train_losses, val_losses, train_accuracies, val_accuracies

"""BLOCK 7: Run Training"""

train_losses, val_losses, train_accuracies, val_accuracies = train(
    model, train_loader, test_loader, criterion, optimizer, epochs=10
)

"""BLOCK 8: Plot Training & Validation Loss and Accuracy Curves"""

import matplotlib.pyplot as plt

def plot_metrics(train_losses, val_losses, train_accuracies, val_accuracies):
    epochs = range(1, len(train_losses) + 1)

    plt.figure(figsize=(14,5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs, train_losses, label='Train Loss')
    plt.plot(epochs, val_losses, label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.title('Loss Curve')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(epochs, train_accuracies, label='Train Accuracy')
    plt.plot(epochs, val_accuracies, label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.title('Accuracy Curve')
    plt.legend()

    plt.show()

plot_metrics(train_losses, val_losses, train_accuracies, val_accuracies)

""" Code for Evaluation & Metrics Table"""

# Evaluation and metrics calculation

# 1. Put model in evaluation mode
model.eval()

# 2. Collect predictions, labels and probabilities
all_preds = []
all_labels = []
all_probs = []

with torch.no_grad():
    for inputs, labels in test_loader:   # <-- use test_loader instead of val_loader
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        probs = torch.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

# 3. Convert lists to numpy arrays for sklearn metrics
all_labels = np.array(all_labels)
all_preds = np.array(all_preds)
all_probs = np.array(all_probs)

"""Confusion Matrix plotting:"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

"""Classification Report:"""

from sklearn.metrics import classification_report
import pandas as pd

report = classification_report(all_labels, all_preds, target_names=class_names, output_dict=True)
df_report = pd.DataFrame(report).transpose()
print(df_report)

"""Multi-class ROC AUC Score:"""

from sklearn.metrics import roc_auc_score

try:
    auc_score = roc_auc_score(all_labels, all_probs, multi_class='ovr')
    print(f"Multi-class ROC AUC Score: {auc_score:.4f}")
except Exception as e:
    print(f"ROC AUC could not be computed: {e}")

"""ROC Curve for Binary Classification only:"""

from sklearn.metrics import roc_curve, auc

if len(class_names) == 2:
    fpr, tpr, _ = roc_curve(all_labels, all_probs[:, 1])
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, label=f'ROC Curve (area = {roc_auc:.4f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("Receiver Operating Characteristic (ROC) Curve")
    plt.legend(loc="lower right")
    plt.show()

"""Save the model separately"""

# Save model state dict only
torch.save(model.state_dict(), "model.pth")

"""Save class weights and class names separately"""

# Save class weights and class names to a dictionary
metadata = {
    'class_weights': class_weights.tolist(),  # convert tensor to list for compatibility
    'class_names': class_names
}

import json
with open("class_metadata.json", "w") as f:
    json.dump(metadata, f)

"""Download both files to your local system"""

from google.colab import files

# Download the model file
files.download("model.pth")

# Download the metadata JSON file
#files.download("class_metadata.json")